# Generated by Django 5.1 on 2024-08-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='content',
            field=models.CharField(default=1, max_length=600),
            preserve_default=False,
        ),
    ]
