# Generated by Django 5.1 on 2024-08-12 18:37

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_contact_address_contact_titlereview_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('squareFeet', models.CharField(max_length=50)),
                ('garage', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('pool', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True)),
                ('build', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to=app.models.custom_upload_to)),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Galleries',
            },
        ),
    ]
